global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "fastapi"
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:8000"]

  - job_name: "streamlit"
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:8501"]
