global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "fastapi"
    file_sd_configs:
      - files:
          - /gceraj/fastapi.json

  - job_name: "streamlit"
    file_sd_configs:
      - files:
          - /gceraj/streamlit.json

