global:
  scrape_interval: 15s
  evaluation_interval: 15s

global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "fastapi"
    file_sd_configs:
      - files:
          - /etc/prometheus/fastapi.json

  - job_name: "streamlit"
    file_sd_configs:
      - files:
          - /etc/prometheus/streamlit.json

